/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


import java.awt.*;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;

/**
 *
 * @author PC-LORENZO
 */
public class UI extends javax.swing.JFrame {

    /**
     * Creates new form UI
     */

    String matricula="null";
    String model="null";

    Controller controller = new Controller();

    public UI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        pPanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        createButton = new javax.swing.JButton();
        matriculaLabel = new javax.swing.JTextField();
        modelLabel = new javax.swing.JTextField();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleLabel.setFont(new java.awt.Font("EA Font v1.5 by Ghettoshark", 0, 36)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(0, 0, 0));
        titleLabel.setText("CONCESIONARIO");
        pPanel.add(titleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 50, 450, 43));

        createButton.setBackground(new java.awt.Color(255, 229, 118));
        createButton.setFont(new java.awt.Font("EA Font v1.5 by Ghettoshark", 0, 36)); // NOI18N
        createButton.setForeground(new java.awt.Color(226, 124, 75));
        createButton.setText("CREAR");
        createButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(183, 72, 44), 4));
        createButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonActionPerformed(evt);
            }
        });
        pPanel.add(createButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 620, 330, 60));

        matriculaLabel.setBackground(new java.awt.Color(255, 229, 118));
        matriculaLabel.setFont(new java.awt.Font("EA Font v1.5 by Ghettoshark", 0, 24)); // NOI18N
        matriculaLabel.setForeground(new java.awt.Color(226, 124, 75));
        matriculaLabel.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        matriculaLabel.setText("MATRICULA");
        matriculaLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(183, 72, 44), 4));
        matriculaLabel.addFocusListener(new FocusListener() {
            @Override
            public void focusGained(FocusEvent e) {
                if (matriculaLabel.getText().equals("MATRICULA")) {
                    matriculaLabel.setText("");
                }
            }
            @Override
            public void focusLost(FocusEvent e) {
                if (matriculaLabel.getText().isEmpty()) {
                    matriculaLabel.setText("MATRICULA");
                }
            }
        });
        pPanel.add(matriculaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 500, 410, 60));

        modelLabel.setBackground(new java.awt.Color(255, 229, 118));
        modelLabel.setFont(new java.awt.Font("EA Font v1.5 by Ghettoshark", 0, 24)); // NOI18N
        modelLabel.setForeground(new java.awt.Color(226, 124, 75));
        modelLabel.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        modelLabel.setText("MODELO");
        modelLabel.setToolTipText("");
        modelLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(183, 72, 44), 4));
        modelLabel.addFocusListener(new FocusListener() {
            @Override
            public void focusGained(FocusEvent e) {
                if (modelLabel.getText().equals("MODELO")) {
                    modelLabel.setText("");
                }
            }
            @Override
            public void focusLost(FocusEvent e) {
                if (modelLabel.getText().isEmpty()) {
                    modelLabel.setText("MODELO");
                }
            }
        });
        pPanel.add(modelLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 420, 410, 60));

        bg.setIcon(new javax.swing.ImageIcon("C:\\Users\\PC-LORENZO\\Downloads\\911.jpg")); // NOI18N
        pPanel.add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(pPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(pPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );



        // Establecer la posición del JFrame
        this.setLocationRelativeTo(null);
        this.setResizable(false);


        pack();
    }// </editor-fold>

    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        controller.crearCoche(modelLabel.getText(),matriculaLabel.getText());
        modelLabel.setText("MODELO");
        matriculaLabel.setText("MATRICULA");
    }


    public static void launch() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JLabel bg;
    private javax.swing.JButton createButton;
    private javax.swing.JTextField matriculaLabel;
    private javax.swing.JTextField modelLabel;
    private javax.swing.JPanel pPanel;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration
}
